name: Deploy Vite app to GitHub Pages

on:
  push:
    branches: [ main ]   # 👈 Change if your default branch is 'master'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build the Vite project
      - name: Build project
        run: npm run build

      # 5. Deploy 'dist' folder to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
